package com.dlb.chess.san.enums;

public enum SanValidationProblem {
  UNKNOWN_ERROR,
  NONE,

  FORMAT_BLANK,
  FORMAT_FIRST_CHARACTER,

  // pawn
  // TODO it is still conceptually wrong to warn for white that d1 is missing promotion information, instead of saying
  // invalid rank
  FORMAT_PAWN_NO_SECOND_CHARACTER,
  FORMAT_PAWN_WRONG_SECOND_CHARACTER,

  // pawn forward non promotion
  FORMAT_PAWN_FORWARD_NON_PROMOTION_OVERLENGTH,

  // pawn forward promotion
  FORMAT_PAWN_FORWARD_PROMOTION_NO_PROMOTION_SYMBOL,
  FORMAT_PAWN_FORWARD_PROMOTION_WRONG_PROMOTION_SYMBOL,
  FORMAT_PAWN_FORWARD_PROMOTION_NO_PROMOTION_PIECE,
  FORMAT_PAWN_FORWARD_PROMOTION_WRONG_PROMOTION_PIECE,
  FORMAT_PAWN_FORWARD_PROMOTION_OVERLENGTH,

  // pawn capture
  FORMAT_PAWN_CAPTURE_NO_FILE,
  FORMAT_PAWN_CAPTURE_WRONG_FILE,
  FORMAT_PAWN_CAPTURE_NO_RANK,
  FORMAT_PAWN_CAPTURE_WRONG_RANK,

  // pawn capture non promotion
  FORMAT_PAWN_CAPTURE_NON_PROMOTION_OVERLENGTH,

  // pawn capture promotion
  FORMAT_PAWN_CAPTURE_PROMOTION_NO_PROMOTION_SYMBOL,
  FORMAT_PAWN_CAPTURE_PROMOTION_WRONG_PROMOTION_SYMBOL,
  FORMAT_PAWN_CAPTURE_PROMOTION_NO_PROMOTION_PIECE,
  FORMAT_PAWN_CAPTURE_PROMOTION_WRONG_PROMOTION_PIECE,
  FORMAT_PAWN_CAPTURE_PROMOTION_OVERLENGTH,

  // king
  // king castling
  FORMAT_KING_CASTLING,

  // king non castling non capture
  FORMAT_KING_NON_CASTLING_NON_CAPTURE_NO_DESTINATION_FILE,
  FORMAT_KING_NON_CASTLING_NON_CAPTURE_WRONG_DESTINATION_FILE,
  FORMAT_KING_NON_CASTLING_NON_CAPTURE_NO_DESTINATION_RANK,
  FORMAT_KING_NON_CASTLING_NON_CAPTURE_WRONG_DESTINATION_RANK,
  FORMAT_KING_NON_CASTLING_NON_CAPTURE_OVERLENGTH,

  // king non castling capture
  FORMAT_KING_NON_CASTLING_CAPTURE_NO_DESTINATION_FILE,
  FORMAT_KING_NON_CASTLING_CAPTURE_WRONG_DESTINATION_FILE,
  FORMAT_KING_NON_CASTLING_CAPTURE_NO_DESTINATION_RANK,
  FORMAT_KING_NON_CASTLING_CAPTURE_WRONG_DESTINATION_RANK,
  FORMAT_KING_NON_CASTLING_CAPTURE_OVERLENGTH,

  // rnbq (R, N, B, Q piece moves)
  FORMAT_RNBQ_NO_SECOND_CHARACTER,
  FORMAT_RNBQ_WRONG_SECOND_CHARACTER,

  // rnbq — rank branch (second char is a rank digit): third char must be 'x' (capture) or a file letter (non-capture)
  FORMAT_RNBQ_RANK_NO_THIRD_CHARACTER,
  FORMAT_RNBQ_RANK_WRONG_THIRD_CHARACTER,

  // rnbq — file branch (second char is a file letter): third char must be a rank digit, a file letter, or 'x'
  FORMAT_RNBQ_FILE_NO_THIRD_CHARACTER,
  FORMAT_RNBQ_FILE_WRONG_THIRD_CHARACTER,

  // rnbq — square branch (second + third chars form [file][rank], a fourth char is present): must be file or 'x'
  FORMAT_RNBQ_SQUARE_WRONG_THIRD_CHARACTER,

  // rnbq non-capture — rank disambiguation (e.g. R2a1)
  FORMAT_RNBQ_NON_CAPTURE_RANK_NO_DESTINATION_RANK,
  FORMAT_RNBQ_NON_CAPTURE_RANK_WRONG_DESTINATION_RANK,
  FORMAT_RNBQ_NON_CAPTURE_RANK_OVERLENGTH,

  // rnbq non-capture — file disambiguation (e.g. Rba1)
  FORMAT_RNBQ_NON_CAPTURE_FILE_NO_DESTINATION_RANK,
  FORMAT_RNBQ_NON_CAPTURE_FILE_WRONG_DESTINATION_RANK,
  FORMAT_RNBQ_NON_CAPTURE_FILE_OVERLENGTH,

  // rnbq non-capture — square disambiguation (e.g. Rb2a1)
  FORMAT_RNBQ_NON_CAPTURE_SQUARE_NO_DESTINATION_RANK,
  FORMAT_RNBQ_NON_CAPTURE_SQUARE_WRONG_DESTINATION_RANK,
  FORMAT_RNBQ_NON_CAPTURE_SQUARE_OVERLENGTH,

  // rnbq capture — no disambiguation (e.g. Rxa1)
  FORMAT_RNBQ_CAPTURE_NO_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_WRONG_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_NO_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_WRONG_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_OVERLENGTH,

  // rnbq capture — rank disambiguation (e.g. R2xa1)
  FORMAT_RNBQ_CAPTURE_RANK_NO_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_RANK_WRONG_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_RANK_NO_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_RANK_WRONG_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_RANK_OVERLENGTH,

  // rnbq capture — file disambiguation (e.g. Rbxa1)
  FORMAT_RNBQ_CAPTURE_FILE_NO_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_FILE_WRONG_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_FILE_NO_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_FILE_WRONG_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_FILE_OVERLENGTH,

  // rnbq capture — square disambiguation (e.g. Rb2xa1)
  FORMAT_RNBQ_CAPTURE_SQUARE_NO_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_SQUARE_WRONG_DESTINATION_FILE,
  FORMAT_RNBQ_CAPTURE_SQUARE_NO_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_SQUARE_WRONG_DESTINATION_RANK,
  FORMAT_RNBQ_CAPTURE_SQUARE_OVERLENGTH,

  // e.g. Ra1a1
  NON_MOVEMENT_RNBQ_SOURCE_SQUARE_EQUALS_DESTINATION_SQUARE,

  MOVEMENT_PAWN_NON_REACHABLE_RANK,
  MOVEMENT_PAWN_NON_REACHABLE_FILE,
  MOVEMENT_RNBQ_FROM_FILE,
  MOVEMENT_RNBQ_FROM_RANK,
  MOVEMENT_RNBQ_FROM_SQUARE,

  EXISTS_PAWN,
  EXISTS_RNBQ_NEITHER,
  EXISTS_RNBQ_FILE,
  EXISTS_RNBQ_RANK,
  EXISTS_RNBQ_SQUARE,

  DESTINATION_OWN_PIECE_NON_CAPTURING,
  DESTINATION_OWN_PIECE_CAPTURING,

  DESTINATION_OPPONENT_KING_NON_CAPTURING,
  DESTINATION_OPPONENT_KING_CAPTURING,

  CAPTURE_SYMBOL_MISSING,
  CAPTURE_SYMBOL_WRONG,

  KING_CASTLING_NOT_POSSIBLE,
  KING_NON_CASTLING_NO_LEGAL_MOVE,

  // TODO does not need both
  PAWN_NON_PROMOTION_NO_LEGAL_MOVE,
  PAWN_PROMOTION_NO_LEGAL_MOVE,

  PIECE_NEITHER_NOT_REACHABLE_SINGLE,
  PIECE_NEITHER_NOT_REACHABLE_MULTIPLE,
  PIECE_NEITHER_KING_LEFT_IN_CHECK_SINGLE,
  PIECE_NEITHER_KING_LEFT_IN_CHECK_MULTIPLE,
  PIECE_NEITHER_KING_EXPOSED_TO_CHECK_SINGLE,
  PIECE_NEITHER_KING_EXPOSED_TO_CHECK_MULTIPLE,
  PIECE_NEITHER_MULTIPLE_LEGAL_MOVES,

  PIECE_FILE_NOT_REACHABLE_SINGLE,
  PIECE_FILE_NOT_REACHABLE_MULTIPLE,
  PIECE_FILE_KING_LEFT_IN_CHECK_SINGLE,
  PIECE_FILE_KING_LEFT_IN_CHECK_MULTIPLE,
  PIECE_FILE_KING_EXPOSED_TO_CHECK_SINGLE,
  PIECE_FILE_KING_EXPOSED_TO_CHECK_MULTIPLE,
  PIECE_FILE_ONLY_ONE_LEGAL_MOVE,
  PIECE_FILE_MUST_USE_RANK,
  PIECE_FILE_MUST_USE_RANK_OR_SQUARE,

  PIECE_RANK_NOT_REACHABLE_SINGLE,
  PIECE_RANK_NOT_REACHABLE_MULTIPLE,
  PIECE_RANK_KING_LEFT_IN_CHECK_SINGLE,
  PIECE_RANK_KING_LEFT_IN_CHECK_MULTIPLE,
  PIECE_RANK_KING_EXPOSED_TO_CHECK_SINGLE,
  PIECE_RANK_KING_EXPOSED_TO_CHECK_MULTIPLE,
  PIECE_RANK_ONLY_ONE_LEGAL_MOVE,
  PIECE_RANK_MUST_USE_FILE,
  PIECE_RANK_MUST_USE_FILE_OR_SQUARE,

  PIECE_SQUARE_NOT_REACHABLE,
  PIECE_SQUARE_KING_LEFT_IN_CHECK,
  PIECE_SQUARE_KING_EXPOSED_TO_CHECK,
  PIECE_SQUARE_ONLY_ONE_LEGAL_MOVE,
  PIECE_SQUARE_FILE_NOT_NECESSARY,
  PIECE_SQUARE_RANK_NOT_NECESSARY,
  PIECE_SQUARE_MUST_USE_FILE_OR_SQUARE,

  CHECKMATE_BUT_CHECK_ONLY,
  CHECKMATE_BUT_NONE,
  CHECK_BUT_CHECKMATE,
  CHECK_BUT_NONE,
  NONE_BUT_CHECKMATE,
  NONE_BUT_CHECK;

}
