package com.dlb.chess.san.enums;

public enum SanValidationProblem {
  UNKNOWN_ERROR,
  NONE,

  FORMAT_BLANK,
  FORMAT_FIRST_CHARACTER,

  // pawn
  // TODO it is still conceptually wrong to warn for white that d1 is missing promotion information, instead of saying
  // invalid rank
  FORMAT_PAWN_NO_SECOND_CHARACTER,
  FORMAT_PAWN_WRONG_SECOND_CHARACTER,

  // pawn forward non promotion
  FORMAT_PAWN_FORWARD_NON_PROMOTION_OVERLENGTH,

  // pawn forward promotion
  FORMAT_PAWN_FORWARD_PROMOTION_NO_PROMOTION_SYMBOL,
  FORMAT_PAWN_FORWARD_PROMOTION_WRONG_PROMOTION_SYMBOL,
  FORMAT_PAWN_FORWARD_PROMOTION_NO_PROMOTION_PIECE,
  FORMAT_PAWN_FORWARD_PROMOTION_WRONG_PROMOTION_PIECE,
  FORMAT_PAWN_FORWARD_PROMOTION_OVERLENGTH,

  // pawn capture
  FORMAT_PAWN_CAPTURE_NO_FILE,
  FORMAT_PAWN_CAPTURE_WRONG_FILE,
  FORMAT_PAWN_CAPTURE_NO_RANK,
  FORMAT_PAWN_CAPTURE_WRONG_RANK,

  // pawn capture non promotion
  FORMAT_PAWN_CAPTURE_NON_PROMOTION_OVERLENGTH,

  // pawn capture promotion
  FORMAT_PAWN_CAPTURE_PROMOTION_NO_PROMOTION_SYMBOL,
  FORMAT_PAWN_CAPTURE_PROMOTION_WRONG_PROMOTION_SYMBOL,
  FORMAT_PAWN_CAPTURE_PROMOTION_NO_PROMOTION_PIECE,
  FORMAT_PAWN_CAPTURE_PROMOTION_WRONG_PROMOTION_PIECE,
  FORMAT_PAWN_CAPTURE_PROMOTION_OVERLENGTH,

  // king
  // king castling
  FORMAT_KING_CASTLING,

  // king non castling
  FORMAT_KING_NON_CASTLING_NO_SECOND_CHARACTER,
  FORMAT_KING_NON_CASTLING_WRONG_SECOND_CHARACTER,

  // king non castling non capture
  FORMAT_KING_NON_CASTLING_NO_DESTINATION_RANK,
  FORMAT_KING_NON_CASTLING_WRONG_DESTINATION_RANK,
  FORMAT_KING_NON_CASTLING_OVERLENGTH_NON_CAPTURE,

  // king non castling capture
  FORMAT_KING_NON_CASTLING_NO_CAPTURE_FILE,
  FORMAT_KING_NON_CASTLING_WRONG_CAPTURE_FILE,
  FORMAT_KING_NON_CASTLING_NO_CAPTURE_RANK,
  FORMAT_KING_NON_CASTLING_WRONG_CAPTURE_RANK,
  FORMAT_KING_NON_CASTLING_OVERLENGTH_CAPTURE,

  FORMAT_PIECE_LENGTH,
  FORMAT_PIECE_DESTINATION,
  FORMAT_PIECE_MIDDLE,

  PAWN_MOVEMENT_NON_REACHABLE_RANK,
  PAWN_MOVEMENT_NON_REACHABLE_FILE,

  INVALID_MOVEMENT_NON_PAWN_FROM_FILE,
  INVALID_MOVEMENT_NON_PAWN_FROM_RANK,
  INVALID_MOVEMENT_NON_PAWN_FROM_SQUARE_NOT_ONTO_ITSELF,
  INVALID_MOVEMENT_NON_PAWN_FROM_SQUARE_ONTO_ITSELF,

  MOVING_ONTO_OWN_PIECE,
  CAPTURING_OWN_PIECE,
  NON_CAPTURING_MOVING_ONTO_OPPONENT_PIECE,
  CAPTURING_MOVING_ONTO_NO_PIECE,
  CAPTURING_OPPONENT_KING,

  KING_CASTLING_NOT_POSSIBLE,
  KING_NON_CASTLING_NO_LEGAL_MOVE,

  // TODO does not need both
  PAWN_NON_PROMOTION_NO_LEGAL_MOVE,
  PAWN_PROMOTION_NO_LEGAL_MOVE,

  PAWN_NO_PIECE_EXISTS,

  PIECE_NEITHER_NO_PIECE_EXISTS,
  PIECE_NEITHER_NOT_REACHABLE_SINGLE,
  PIECE_NEITHER_NOT_REACHABLE_MULTIPLE,
  PIECE_NEITHER_KING_LEFT_IN_CHECK_SINGLE,
  PIECE_NEITHER_KING_LEFT_IN_CHECK_MULTIPLE,
  PIECE_NEITHER_KING_EXPOSED_TO_CHECK_SINGLE,
  PIECE_NEITHER_KING_EXPOSED_TO_CHECK_MULTIPLE,
  PIECE_NEITHER_MULTIPLE_LEGAL_MOVES,

  PIECE_FILE_NO_PIECE_EXISTS,
  PIECE_FILE_NOT_REACHABLE_SINGLE,
  PIECE_FILE_NOT_REACHABLE_MULTIPLE,
  PIECE_FILE_KING_LEFT_IN_CHECK_SINGLE,
  PIECE_FILE_KING_LEFT_IN_CHECK_MULTIPLE,
  PIECE_FILE_KING_EXPOSED_TO_CHECK_SINGLE,
  PIECE_FILE_KING_EXPOSED_TO_CHECK_MULTIPLE,
  PIECE_FILE_ONLY_ONE_LEGAL_MOVE,
  PIECE_FILE_MUST_USE_RANK,
  PIECE_FILE_MUST_USE_RANK_OR_SQUARE,

  PIECE_RANK_NO_PIECE_EXISTS,
  PIECE_RANK_NOT_REACHABLE_SINGLE,
  PIECE_RANK_NOT_REACHABLE_MULTIPLE,
  PIECE_RANK_KING_LEFT_IN_CHECK_SINGLE,
  PIECE_RANK_KING_LEFT_IN_CHECK_MULTIPLE,
  PIECE_RANK_KING_EXPOSED_TO_CHECK_SINGLE,
  PIECE_RANK_KING_EXPOSED_TO_CHECK_MULTIPLE,
  PIECE_RANK_ONLY_ONE_LEGAL_MOVE,
  PIECE_RANK_MUST_USE_FILE,
  PIECE_RANK_MUST_USE_FILE_OR_SQUARE,

  PIECE_SQUARE_NO_PIECE_EXISTS,
  PIECE_SQUARE_NOT_REACHABLE,
  PIECE_SQUARE_KING_LEFT_IN_CHECK,
  PIECE_SQUARE_KING_EXPOSED_TO_CHECK,
  PIECE_SQUARE_ONLY_ONE_LEGAL_MOVE,
  PIECE_SQUARE_FILE_NOT_NECESSARY,
  PIECE_SQUARE_RANK_NOT_NECESSARY,
  PIECE_SQUARE_MUST_USE_FILE_OR_SQUARE,

  CHECKMATE_BUT_CHECK_ONLY,
  CHECKMATE_BUT_NONE,
  CHECK_BUT_CHECKMATE,
  CHECK_BUT_NONE,
  NONE_BUT_CHECKMATE,
  NONE_BUT_CHECK;

}
