package com.dlb.chess.common.constants;

import com.dlb.chess.board.enums.File;
import com.dlb.chess.board.enums.Piece;
import com.dlb.chess.board.enums.PieceType;
import com.dlb.chess.board.enums.Rank;
import com.dlb.chess.board.enums.Side;
import com.dlb.chess.board.enums.Square;

public interface EnumConstants {
  Square A1 = Square.A1;
  Square B1 = Square.B1;
  Square C1 = Square.C1;
  Square D1 = Square.D1;
  Square E1 = Square.E1;
  Square F1 = Square.F1;
  Square G1 = Square.G1;
  Square H1 = Square.H1;
  Square A2 = Square.A2;
  Square B2 = Square.B2;
  Square C2 = Square.C2;
  Square D2 = Square.D2;
  Square E2 = Square.E2;
  Square F2 = Square.F2;
  Square G2 = Square.G2;
  Square H2 = Square.H2;
  Square A3 = Square.A3;
  Square B3 = Square.B3;
  Square C3 = Square.C3;
  Square D3 = Square.D3;
  Square E3 = Square.E3;
  Square F3 = Square.F3;
  Square G3 = Square.G3;
  Square H3 = Square.H3;
  Square A4 = Square.A4;
  Square B4 = Square.B4;
  Square C4 = Square.C4;
  Square D4 = Square.D4;
  Square E4 = Square.E4;
  Square F4 = Square.F4;
  Square G4 = Square.G4;
  Square H4 = Square.H4;
  Square A5 = Square.A5;
  Square B5 = Square.B5;
  Square C5 = Square.C5;
  Square D5 = Square.D5;
  Square E5 = Square.E5;
  Square F5 = Square.F5;
  Square G5 = Square.G5;
  Square H5 = Square.H5;
  Square A6 = Square.A6;
  Square B6 = Square.B6;
  Square C6 = Square.C6;
  Square D6 = Square.D6;
  Square E6 = Square.E6;
  Square F6 = Square.F6;
  Square G6 = Square.G6;
  Square H6 = Square.H6;
  Square A7 = Square.A7;
  Square B7 = Square.B7;
  Square C7 = Square.C7;
  Square D7 = Square.D7;
  Square E7 = Square.E7;
  Square F7 = Square.F7;
  Square G7 = Square.G7;
  Square H7 = Square.H7;
  Square A8 = Square.A8;
  Square B8 = Square.B8;
  Square C8 = Square.C8;
  Square D8 = Square.D8;
  Square E8 = Square.E8;
  Square F8 = Square.F8;
  Square G8 = Square.G8;
  Square H8 = Square.H8;

  Side WHITE = Side.WHITE;
  Side BLACK = Side.BLACK;

  Piece WHITE_ROOK = Piece.WHITE_ROOK;
  Piece WHITE_KNIGHT = Piece.WHITE_KNIGHT;
  Piece WHITE_BISHOP = Piece.WHITE_BISHOP;
  Piece WHITE_QUEEN = Piece.WHITE_QUEEN;
  Piece WHITE_KING = Piece.WHITE_KING;
  Piece WHITE_PAWN = Piece.WHITE_PAWN;
  Piece BLACK_ROOK = Piece.BLACK_ROOK;
  Piece BLACK_KNIGHT = Piece.BLACK_KNIGHT;
  Piece BLACK_BISHOP = Piece.BLACK_BISHOP;
  Piece BLACK_QUEEN = Piece.BLACK_QUEEN;
  Piece BLACK_KING = Piece.BLACK_KING;
  Piece BLACK_PAWN = Piece.BLACK_PAWN;
  Piece PIECE_NONE = Piece.NONE;

  PieceType ROOK = PieceType.ROOK;
  PieceType KNIGHT = PieceType.KNIGHT;
  PieceType BISHOP = PieceType.BISHOP;
  PieceType QUEEN = PieceType.QUEEN;
  PieceType KING = PieceType.KING;
  PieceType PAWN = PieceType.PAWN;

  Rank RANK_1 = Rank.RANK_1;
  Rank RANK_2 = Rank.RANK_2;
  Rank RANK_3 = Rank.RANK_3;
  Rank RANK_4 = Rank.RANK_4;
  Rank RANK_5 = Rank.RANK_5;
  Rank RANK_6 = Rank.RANK_6;
  Rank RANK_7 = Rank.RANK_7;
  Rank RANK_8 = Rank.RANK_8;
  Rank RANK_NONE = Rank.NONE;

  File FILE_A = File.FILE_A;
  File FILE_B = File.FILE_B;
  File FILE_C = File.FILE_C;
  File FILE_D = File.FILE_D;
  File FILE_E = File.FILE_E;
  File FILE_F = File.FILE_F;
  File FILE_G = File.FILE_G;
  File FILE_H = File.FILE_H;
  File FILE_NONE = File.NONE;

}
