package com.dlb.chess.enums;

public enum MoveCheck {
  SUCCESS,

  MOVE_SPEC_NON_PAWN_PROMOTION_PIECE_SET,
  MOVE_SPEC_PAWN_PROMOTION_NO_PROMOTION_PIECE,
  MOVE_SPEC_PAWN_NON_PROMOTION_PROMOTION_PIECE,

  MOVE_SPEC_FROM_SQUARE_EMPTY,
  MOVE_SPEC_FROM_SQUARE_OCCUPIED_BY_OPPONENT,

  MOVEMENT_NOT_POSSIBLE,
  MOVEMENT_TO_SQUARE_OCCUPIED_BY_OWN_PIECE,

  MOVEMENT_LONG_RANGE_PIECE_JUMPS_OVER_PIECE,

  ALL_BUT_KING_KING_LEFT_IN_CHECK,
  ALL_BUT_KING_KING_EXPOSED_TO_CHECK,

  MOVEMENT_PAWN_FORWARD_TWO_SQUARE_JUMP_OVER_SQUARE_ONLY_NOT_EMPTY,
  MOVEMENT_PAWN_FORWARD_TWO_SQUARE_TO_SQUARE_ONLY_NOT_EMPTY,
  MOVEMENT_PAWN_FORWARD_TWO_SQUARE_BOTH_SQUARE_NOT_EMPTY,

  MOVEMENT_PAWN_FORWARD_ONE_SQUARE_TO_SQUARE_NOT_EMPTY_OWN_PIECE,
  MOVEMENT_PAWN_FORWARD_ONE_SQUARE_TO_SQUARE_NOT_EMPTY_OPPONENT_PIECE,

  MOVEMENT_PAWN_DIAGONAL_OWN_PIECE,

  MOVEMENT_PAWN_EN_PASSANT_WRONG_RANK,
  MOVEMENT_PAWN_EN_PASSANT_NO_IMMEDIATE_BEFORE_TWO_SQUARE_ADVANCE,

  KING_CAPTURES_GUARDED_PIECE,
  KING_MOVES_NEXT_TO_OPPONENT_KING,
  KING_MOVES_TO_ATTACKED_EMPTY_SQUARE,

  // castling refusal reasons — FINAL means the castling right is lost permanently, with the
  // suffix naming why the right was lost; TEMPORARY means the board state blocks castling now
  // but castling may become possible again. The castling cases are overlapping so we check in
  // order numbered.
  KING_CASTLING_FINAL_NO_RIGHT_KING_MOVED,
  KING_CASTLING_FINAL_NO_RIGHT_ROOK_MOVED,
  KING_CASTLING_FINAL_NO_RIGHT_ROOK_CAPTURED,
  KING_CASTLING_FINAL_NO_RIGHT_CASTLED,
  KING_CASTLING_FINAL_NO_RIGHT_UNKNOWN_FEN_IMPORT,
  KING_CASTLING_TEMPORARY_SQUARES_NOT_EMPTY,
  KING_CASTLING_TEMPORARY_KING_IN_CHECK,
  KING_CASTLING_TEMPORARY_KING_TRAVELS_THROUGH_CHECK,
  KING_CASTLING_TEMPORARY_KING_ENDS_IN_CHECK,
}
