package com.dlb.chess.enums;

public enum MoveCheck {
  SUCCESS,

  BASIC_NON_PAWN_PROMOTION_PIECE_SET,
  PAWN_PROMOTION_MOVE_NO_PROMOTION_PIECE,
  PAWN_NON_PROMOTION_MOVE_PROMOTION_PIECE,

  BASIC_MOVING_PIECE_NONE,
  BASIC_MOVING_PIECE_OPPONENT,

  ALL_MOVEMENT_NOT_POSSIBLE,
  ALL_TO_SQUARE_OCCUPIED_BY_OWN_PIECE,

  LONG_RANGE_PIECES_CANNOT_JUMP_OVER_PIECES,

  ALL_BUT_KING_KING_LEFT_IN_CHECK,
  ALL_BUT_KING_KING_EXPOSED_TO_CHECK,

  PAWN_FORWARD_TWO_SQUARE_JUMP_OVER_SQUARE_ONLY_NOT_EMPTY,
  PAWN_FORWARD_TWO_SQUARE_TO_SQUARE_ONLY_NOT_EMPTY,
  PAWN_FORWARD_TWO_SQUARE_BOTH_SQUARE_NOT_EMPTY,

  PAWN_FORWARD_ONE_SQUARE_TO_SQUARE_NOT_EMPTY_OWN_PIECE,
  PAWN_FORWARD_ONE_SQUARE_TO_SQUARE_NOT_EMPTY_OPPONENT_PIECE,

  PAWN_DIAGONAL_OWN_PIECE,
  PAWN_EN_PASSANT_CAPTURE_WRONG_RANK,

  PAWN_EN_PASSANT_CAPTURE_NO_IMMEDIATE_BEFORE_TWO_SQUARE_ADVANCE,

  KING_CAPTURES_GUARDED_PIECE,
  KING_MOVES_NEXT_TO_OPPONENT_KING,
  KING_MOVES_INTO_CHECK,

  KING_IN_CHECK_TO_EMPTY_ATTACKED_SQUARE_NO_LEGAL_MOVES,
  KING_IN_CHECK_TO_EMPTY_ATTACKED_SQUARE_LEGAL_MOVES,

  // castling refusal reasons — FINAL means the castling right is lost permanently;
  // TEMPORARY means the board state blocks castling now but castling may become possible again.
  // The castling cases are overlapping so we check in order numbered.
  KING_CASTLING_FINAL_NO_RIGHT,
  KING_CASTLING_TEMPORARY_SQUARES_NOT_EMPTY,
  KING_CASTLING_TEMPORARY_KING_IN_CHECK,
  KING_CASTLING_TEMPORARY_KING_TRAVELS_THROUGH_CHECK,
  KING_CASTLING_TEMPORARY_KING_ENDS_IN_CHECK,
}
