package com.dlb.chess.pgn.parser.enums;

public enum LenientPgnParserValidationProblem {
  UNKNOWN_ERROR,
  OK,
  TAG_REAPPEAR,
  TAG_FORMAT_INVALID,
  TAG_NAME_NOT_UNIQUE,
  TAG_RESULT_VALUE_INVALID,
  TAG_RESULT_BOTH_SET_BUT_DIFFERENT,
  TAG_SET_UP_VALUE_INVALID,
  TAG_SET_UP_VALUE_ZERO_BUT_FEN_PROVIDED,
  MOVETEXT_COMMENTARY_START_BRACE_NOT_FOLLOWED_BY_END_BRACE,
  MOVETEXT_COMMENTARY_END_BRACE_WITHOUT_START_BRACE,
  MOVETEXT_COMMENTARY_CONTAINS_START_BRACE,
  MOVETEXT_COMMENTARY_NOT_ALLOWED_IN_SAN,
  MOVETEXT_CONTENT_AFTER_TERMINATION,
  EXCEPTION_CAUGHT_FROM_STRICT_VALIDATION,
  SAN
}
