package com.dlb.chess.common.enums;

public enum FenAdvancedFurtherValidationProblem {
  SUCCESS,
  INVALID_HALF_MOVE_CLOCK_TOO_BIG_RELATIVE_TO_FULL_MOVE_NUMBER,
  INVALID_FULL_MOVE_NUMBER_ONE_WHITE_IN_NON_STARTING_POSITION,
  INVALID_FULL_MOVE_NUMBER_ONE_BLACK_IN_NON_POSSIBLE_POSITION
}
