package com.dlb.chess.common.enums;

public enum GameStatus {

  CHECKMATE,
  STALEMATE,
  INSUFFICIENT_MATERIAL_BOTH,
  INSUFFICIENT_MATERIAL_MADE_THE_MOVE_ONLY,
  INSUFFICIENT_MATERIAL_NOT_MADE_THE_MOVE_ONLY,
  FIVE_FOLD_REPETITION_RULE,
  SEVENTY_FIVE_MOVE_RULE,
  OTHER
}
