package com.dlb.chess.pgn.reader.enums;

public enum PgnReaderValidationProblem {
  TAG_REAPPEAR,
  TAG_FORMAT_INVALID,
  TAG_NAME_NOT_UNIQUE,
  TAG_RESULT_VALUE_INVALID,
  TAG_RESULT_BOTH_SET_BUT_DIFFERENT,
  TAG_SET_UP_VALUE_INVALID,
  TAG_SET_UP_VALUE_ZERO_BUT_FEN_PROVIDED,
  EXCEPTION_CATCHED_FROM_STRICT_VALIDATION,
  SAN
}
