package com.dlb.chess.pgn;

public enum StrictPgnParserValidationProblem {
  UNKNOWN_ERROR,
  OK,
  /**
   * The PGN input is empty — zero bytes, only the UTF-8 BOM, or whitespace-only (spaces, tabs, newlines in any
   * combination). The strict parser refuses these inputs at the top of the structural pre-scan because they carry no
   * signal — the {@code FILE_EMPTY_LINE_*} diagnostics are about the strict two-blank-lines layout and don't apply
   * when there's nothing to lay out in the first place. Symmetric with
   * {@link LenientPgnParserValidationProblem#FILE_EMPTY}.
   */
  FILE_EMPTY,
  FILE_EMPTY_LINE_CANNOT_START_WITH,
  FILE_EMPTY_LINE_MUST_END_WITH,
  FILE_EMPTY_LINE_EXACTLY_TWO,
  FILE_EMPTY_LINE_NOT_CONSECUTIVE,
  TAG_FORMAT_INVALID,
  TAG_FORMAT_NOT_STARTING_WITH_LEFT_SQUARE_BRACKET,
  TAG_FORMAT_NOT_ENDING_WITH_RIGHT_SQUARE_BRACKET,
  TAG_FORMAT_LEFT_SQUARE_BRACKET_FOLLOWED_BY_SPACE,
  TAG_NAME_FIRST_CHARACTER,
  TAG_NAME_EXCEEDS_MAXIMUM_LENGTH,
  TAG_NAME_NOT_UNIQUE,
  TAG_RESULT_MISSING,
  TAG_RESULT_VALUE_INVALID,
  TAG_SET_UP_VALUE_INVALID,
  TAG_SET_UP_REQUIRES_FEN_TAG_BUT_MISSING,
  TAG_SET_UP_REQUIRES_FEN_TAG_BUT_FEN_INVALID,
  TAG_FEN_NOT_REQUIRED_BUT_SET,
  MOVETEXT_TERMINATION_INVALID,
  MOVETEXT_MOVE_NUMBER_DOES_NOT_BEGIN_WITH_CORRECT,
  MOVETEXT_MOVE_NUMBER_DOES_NOT_BEGIN_WITH_WHITE_MOVE,
  MOVETEXT_MOVE_NUMBER_DOES_NOT_BEGIN_WITH_BLACK_MOVE,
  MOVETEXT_MOVE_NUMBER_DOES_NOT_CONTINUE_AS_EXPECTED,
  MOVETEXT_MOVE_NUMBER_ENDS_AFTER,
  MOVETEXT_MOVE_NUMBER_FOR_BLACK_NON_INITIAL_MOVE,
  MOVETEXT_MOVE_NUMBER_REQUIRED_AFTER_COMMENTARY,
  MOVETEXT_SAN_CHARACTER_INVALID,
  MOVETEXT_SAN_EMPTY,
  MOVETEXT_SAN_FOLLOWED_BY_SPACE_BUT_ENDS_AFTER,
  MOVETEXT_SAN_LENGTH_INVALID,
  MOVETEXT_MOVE_SUFFIX_ANNOTATION_INVALID,
  MOVETEXT_COMMENTARY_ENDS_AFTER_START_BRACE,
  MOVETEXT_COMMENTARY_NOT_FOLLOWED_BY_SPACE,
  MOVETEXT_COMMENTARY_FOLLOWED_BY_SPACE_BUT_ENDING,
  MOVETEXT_COMMENTARY_FOLLOWED_BY_TWO_SPACES,
  MOVETEXT_COMMENTARY_NOT_FOLLOWED_BY_VALUE,
  MOVETEXT_COMMENTARY_START_BRACE_NOT_FOLLOWED_BY_END_BRACE,
  MOVETEXT_COMMENTARY_END_BRACE_WITHOUT_START_BRACE,
  MOVETEXT_COMMENTARY_CONTAINS_FORBIDDEN_CHARACTER,
  MOVETEXT_COMMENTARY_NOT_ALLOWED_IN_SAN,
  MOVETEXT_CONTENT_AFTER_TERMINATION,
  MOVETEXT_UNEXPECTED_FORMAT,
  SAN

}
